/**
 * This file was generated by the Jeddict
 */
package ch.zhaw.gpi.eumzugplattform.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author Bekim
 */
@Entity(name="Document")
@Table(name = "DOCUMENT")
public class DocumentEntity implements Serializable {

    @Column(name = "DOCUMENT_ID", unique = true, nullable = false)
    @Id
    private Long documentId;

    @Column(name = "NAME", unique = true, nullable = false)
    @Basic
    private String name;

    public Long getDocumentId() {
        return this.documentId;
    }

    public void setDocumentId(Long documentId) {
        this.documentId = documentId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}