/**
 * This file was generated by the Jeddict
 */
package ch.zhaw.gpi.eumzugplattform.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author Bekim
 */
@Entity(name="MunicipalityDocument")
@Table(name = "MUNICIPALITY_DOCUMENT")
public class MunicipalityDocumentRelationEntity implements Serializable {

    @Column(name = "MUNICIPALITY_DOCUMENT_ID", unique = true, nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long municipalityDocumentId;

    @Column(name = "MARRIAGE_CONDITION", nullable = false)
    @Basic
    private Boolean marriageCondition;

    @Column(name = "CHILDREN_CONDITION", nullable = false)
    @Basic
    private Boolean childrenCondition;

    @Column(name = "STRANGER_CONDITION", nullable = false)
    @Basic
    private Boolean strangerCondition;

    @ManyToOne
    @JoinColumn(name = "DOCUMENT_ID")
    private DocumentEntity documentEntity;

    public Long getMunicipalityDocumentId() {
        return this.municipalityDocumentId;
    }

    public void setMunicipalityDocumentId(Long municipalityDocumentId) {
        this.municipalityDocumentId = municipalityDocumentId;
    }

    public Boolean isMarriageCondition() {
        return this.marriageCondition;
    }

    public void setMarriageCondition(Boolean marriageCondition) {
        this.marriageCondition = marriageCondition;
    }

    public Boolean isChildrenCondition() {
        return this.childrenCondition;
    }

    public void setChildrenCondition(Boolean childrenCondition) {
        this.childrenCondition = childrenCondition;
    }

    public Boolean isStrangerCondition() {
        return this.strangerCondition;
    }

    public void setStrangerCondition(Boolean strangerCondition) {
        this.strangerCondition = strangerCondition;
    }

    public DocumentEntity getDocumentEntity() {
        return this.documentEntity;
    }

    public void setDocumentEntity(DocumentEntity documentEntity) {
        this.documentEntity = documentEntity;
    }

}