/**
 * This file was generated by the Jeddict
 */
package ch.zhaw.gpi.eumzugplattform.entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author scep
 */
@Entity(name="Municipality")
public class MunicipalityEntity implements Serializable {

    @Column(unique = true, nullable = false)
    @Id
    @Min(value = 1)
    @Max(value = 9999)
    private int municipalityId;

    @Column(nullable = false)
    @Basic
    @NotNull
    @Size(min = 1, max = 40)
    private String municipalityName;

    @Basic
    @Min(value = 0)
    @Max(value = 50)
    private int feeMove;

    @Basic
    @Min(value = 0)
    @Max(value = 50)
    private int feeMoveOut;

    @Basic
    @Min(value = 0)
    @Max(value = 50)
    private int feeMoveIn;

    @OneToMany(targetEntity = MunicipalityDocumentRelationEntity.class)
    @JoinColumn(name = "MUNICIPALITY_ID")
    private List<MunicipalityDocumentRelationEntity> municipalityDocumentRelationEntities;

    public int getMunicipalityId() {
        return this.municipalityId;
    }

    public void setMunicipalityId(int municipalityId) {
        this.municipalityId = municipalityId;
    }

    public String getMunicipalityName() {
        return this.municipalityName;
    }

    public void setMunicipalityName(String municipalityName) {
        this.municipalityName = municipalityName;
    }

    public int getFeeMove() {
        return this.feeMove;
    }

    public void setFeeMove(int feeMove) {
        this.feeMove = feeMove;
    }

    public int getFeeMoveOut() {
        return this.feeMoveOut;
    }

    public void setFeeMoveOut(int feeMoveOut) {
        this.feeMoveOut = feeMoveOut;
    }

    public int getFeeMoveIn() {
        return this.feeMoveIn;
    }

    public void setFeeMoveIn(int feeMoveIn) {
        this.feeMoveIn = feeMoveIn;
    }

    public List<MunicipalityDocumentRelationEntity> getMunicipalityDocumentRelationEntities() {
        if (municipalityDocumentRelationEntities == null) {
            municipalityDocumentRelationEntities = new ArrayList<>();
        }
        return this.municipalityDocumentRelationEntities;
    }

    public void setMunicipalityDocumentRelationEntities(List<MunicipalityDocumentRelationEntity> municipalityDocumentRelationEntities) {
        this.municipalityDocumentRelationEntities = municipalityDocumentRelationEntities;
    }

    public void addMunicipalityDocumentRelationEntity(MunicipalityDocumentRelationEntity municipalityDocumentRelationEntity) {
        getMunicipalityDocumentRelationEntities().add(municipalityDocumentRelationEntity);
    }

    public void removeMunicipalityDocumentRelationEntity(MunicipalityDocumentRelationEntity municipalityDocumentRelationEntity) {
        getMunicipalityDocumentRelationEntities().remove(municipalityDocumentRelationEntity);
    }

}