/**
 * This file was generated by the Jeddict
 */
package ch.zhaw.gpi.eumzugplattform.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.Optional;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author scep
 */
@Entity(name = "Person")
public class PersonEntity implements Serializable {

    @Id
    @Size(min = 1, max = 36)
    private String localPersonId;

    @Basic
    @Min(value = 7560000000001L)
    @Max(value = 7569999999999L)
    private Long vn;

    @Column(nullable = false)
    @Basic
    @NotNull
    @Size(min = 1, max = 100)
    private String firstName;

    @Column(nullable = false)
    @Basic
    @NotNull
    @Size(min = 1, max = 100)
    private String officialName;

    /**
     * 1 (mÃ¤nnlich), 2 (weiblich), 3 (unbestimmt)
     */
    @Column(nullable = false)
    @Basic
    @NotNull
    @Min(value = 1)
    @Max(value = 3)
    private int sex;

    @Column(nullable = false)
    @Basic
    @Temporal(TemporalType.DATE)
    private Date dateOfBirth;

    public String getLocalPersonId() {
        return this.localPersonId;
    }

    public void setLocalPersonId(String localPersonId) {
        this.localPersonId = localPersonId;
    }

    public Optional<Long> getVn() {
        return Optional.ofNullable(this.vn);
    }

    public void setVn(Long vn) {
        this.vn = vn;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getOfficialName() {
        return this.officialName;
    }

    public void setOfficialName(String officialName) {
        this.officialName = officialName;
    }

    public int getSex() {
        return this.sex;
    }

    public void setSex(int sex) {
        this.sex = sex;
    }

    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

}