/**
 * This file was generated by the Jeddict
 */
package ch.zhaw.gpi.eumzugplattform.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author scep
 */
@Entity(name="TransactionLog")
public class TransactionLogEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long logId;

    @Column(nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date logTimeStamp;

    @Column(nullable = false)
    @Basic
    @NotNull
    @Size(min = 1, max = 100)
    private String status;

    @ManyToOne
    @JoinColumn(name = "LOCALPERSONID")
    private PersonEntity personEntity;

    public Long getLogId() {
        return this.logId;
    }

    public void setLogId(Long logId) {
        this.logId = logId;
    }

    public Date getLogTimeStamp() {
        return this.logTimeStamp;
    }

    public void setLogTimeStamp(Date logTimeStamp) {
        this.logTimeStamp = logTimeStamp;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public PersonEntity getPersonEntity() {
        return this.personEntity;
    }

    public void setPersonEntity(PersonEntity personEntity) {
        this.personEntity = personEntity;
    }

}